### ISSUE TITLE
Cannot read the given data files using klepto

### ISSUE THREAD

**Issue by BuddhiWathsala** [DerekQXu/GLSearch#2]
When I tried to read the [given data files](https://drive.google.com/drive/folders/1l7_WmO54gPHZ4YwzOqewZtZhWIxn44ZV?usp=sharing) using Python Klepto, it returns an empty map.

I used the following code.
```python
from klepto.archives import *

file = file_archive("duogexf__roadNet-CA_rw_978513_1;roadNet-CA_rw_978513_2_train_test_mcs_bfs_one_hot_local_degree_profile_None.klepto")
file.load()

print(file)
```

The output:
```sh
file_archive('duogexf__roadNet-CA_rw_978513_1;roadNet-CA_rw_978513_2_train_test_mcs_bfs_one_hot_local_degree_profile_None.klepto', {}, cached=True)
```

Do you have any idea what went wrong here?

I used the same klepto version as in your `requirements.txt`, which is `0.1.6`

**Comment by DerekQXu** [comment]
To load the klepto, the `OurModelData` object found on `line 13` of `model/OurMCS/data_model.py` must be defined.

For example:
```
from config import FLAGS
import torch
from torch.utils.data import Dataset as TorchDataset

import klepto

class OurModelData(TorchDataset):
    """Stores a list of graph id pairs with known pairwise results."""

    def __init__(self, dataset, num_node_feat):
        self.dataset, self.num_node_feat = dataset, num_node_feat
        gid_pairs = list(self.dataset.pairs.keys())
        self.gid1gid2_list = torch.tensor(
            sorted(gid_pairs),
            device=FLAGS.device)  # takes a while to move to GPU

    def __len__(self):
        return len(self.gid1gid2_list)

    def __getitem__(self, idx):
        return self.gid1gid2_list[idx]
...

file = klepto.archives.file_archive("duogexf__roadNet-CA_rw_978513_1;roadNet-CA_rw_978513_2_train_test_mcs_bfs_one_hot_local_degree_profile_None.klepto")
file.load()
print(file)
```

Hope this helps!

**Comment by BuddhiWathsala** [comment]
> To load the klepto, the `OurModelData` object found on `line 13` of `model/OurMCS/data_model.py` must be defined.
> 
> For example:
> 
> ```
> from config import FLAGS
> import torch
> from torch.utils.data import Dataset as TorchDataset
> 
> import klepto
> 
> class OurModelData(TorchDataset):
>     """Stores a list of graph id pairs with known pairwise results."""
> 
>     def __init__(self, dataset, num_node_feat):
>         self.dataset, self.num_node_feat = dataset, num_node_feat
>         gid_pairs = list(self.dataset.pairs.keys())
>         self.gid1gid2_list = torch.tensor(
>             sorted(gid_pairs),
>             device=FLAGS.device)  # takes a while to move to GPU
> 
>     def __len__(self):
>         return len(self.gid1gid2_list)
> 
>     def __getitem__(self, idx):
>         return self.gid1gid2_list[idx]
> ...
> 
> file = klepto.archives.file_archive("duogexf__roadNet-CA_rw_978513_1;roadNet-CA_rw_978513_2_train_test_mcs_bfs_one_hot_local_degree_profile_None.klepto")
> file.load()
> print(file)
> ```
> 
> Hope this helps!

I tried this but it didn't work. I think it `OurModelData` class is never used when saving the klepto file. In fact, you didn't even use the `OurModelData` when saving the file. So, the class doesn't have any effect on klepto file saving.

>```
>file = klepto.archives.file_archive("duogexf__roadNet-CA_rw_978513_1;roadNet->CA_rw_978513_2_train_test_mcs_bfs_one_hot_local_degree_profile_None.klepto")
>file.load()
>print(file)
>```

**Comment by BuddhiWathsala** [comment]
Klepto files should be easily loaded as demonstrated in [here [1]](https://stackoverflow.com/questions/29270772/python-saving-and-editing-with-klepto). The example in [[1]](https://stackoverflow.com/questions/29270772/python-saving-and-editing-with-klepto) works for me. But I cannot load the data you shared like [[1]](https://stackoverflow.com/questions/29270772/python-saving-and-editing-with-klepto).

## References
[1] https://stackoverflow.com/questions/29270772/python-saving-and-editing-with-klepto

**Comment by DerekQXu** [comment]
The klepto loading code is the same as the one you cited, but `OurModelData` needs to be defined before calling `file_archive(...)`, otherwise it will return an empty dictionary.

The klepto file stores `OurModelData` objects. Running the code snippet, https://github.com/DerekQXu/GLSearch/issues/2#issuecomment-1461647379, should return the following:
```
file_archive('duogexf_roadNet-CA_rw_978513_1_roadNet-CA_rw_978513_2_train_test_mcs_bfs_one_hot_local_degree_profile_None.klepto', {'train_data': <data_model.OurModelData object at 0x7f8c3bd4f3c8>, 'test_data': <data_model.OurModelData object at 0x7f8b6bb458d0>}, cached=True)
```

Some ideas I think may resolve this issue:
1) Is the file path is pointed to the correct location? Sometimes the file gets renamed after downloading from Google Drive. We updated the README with this issue.
2) Are the other libraries the same version? If there is a version mismatch for torch or other libraries used by `OurModelData`, the object mismatch may cause klepto to silently fail. We just released a Docker file to make this setup easier: 72784e112afdbaee99736c2df9dab9c06bba21f8.
3) Try using our Docker environment, as this ensures our two environments are as similar as possible.

Hope this helps, and feel free to let me know if this issue still persists! Thanks!

**Comment by BuddhiWathsala** [comment]
Thanks for your effort and suggestions. However, even when I ran the experiment with the given docker container, still, it gave the same issue.

I change your docker file to reproduce this issue easily in the given docker environment. I did the following changes to the Dockerfile.

https://github.com/BuddhiWathsala/GLSearch/commit/30cdc3b36e12aa34b60d2f19598ad29f282f6ffc

Also, I published a docker image with the above changes. You could easily check this by running the following command.

```sh
$ docker run buddhiwathsala/glsearch:0.0.1
```
It will give you the following output.

```sh
Reproduce the issue https://github.com/DerekQXu/GLSearch/issues/2
file_archive('mutag_train_test_mcs_bfs_one_hot_local_degree_profile_None.klepto', {}, cached=True)
```

**Comment by DerekQXu** [comment]
Thank you so much for providing this code! I was able to reproduce the error.

It seems in addition to the `OurModelData` class, we also need to import `FLAGS` from `config.py` for the klepto loading to work. Thanks for pointing out this issue!

The following fix should work (within workspace directory of the docker environment):
```
$ sed -i '1s/^/from config import FLAGS\n/' load/test.py # append FLAGS loading to test.py
$ cp load/* model/OurMCS/ # move test.py and data into model/OurMCS
$ cd model/OurMCS
$ python3 test.py
did not load pdb data
did not load seaborn
Reproduce the issue https://github.com/DerekQXu/GLSearch/issues/2
file_archive('mutag_train_test_mcs_bfs_one_hot_local_degree_profile_None.klepto', {'train_data': <data_model.OurModelData object at 0x7ff73fa8d320>, 'test_data': <data_model.OurModelData object at 0x7ff6697db400>}, cached=True)
```

Feel free to let me know if there's still issues! Thanks!

**Comment by BuddhiWathsala** [comment]
> Thank you so much for providing this code! I was able to reproduce the error.
> 
> It seems in addition to the `OurModelData` class, we also need to import `FLAGS` from `config.py` for the klepto loading to work. Thanks for pointing out this issue!
> 
> The following fix should work (within workspace directory of the docker environment):
> 
> ```
> $ sed -i '1s/^/from config import FLAGS\n/' load/test.py # append FLAGS loading to test.py
> $ cp load/* model/OurMCS/ # move test.py and data into model/OurMCS
> $ cd model/OurMCS
> $ python3 test.py
> did not load pdb data
> did not load seaborn
> Reproduce the issue https://github.com/DerekQXu/GLSearch/issues/2
> file_archive('mutag_train_test_mcs_bfs_one_hot_local_degree_profile_None.klepto', {'train_data': <data_model.OurModelData object at 0x7ff73fa8d320>, 'test_data': <data_model.OurModelData object at 0x7ff6697db400>}, cached=True)
> ```
> 
> Feel free to let me know if there's still issues! Thanks!

I tried the method that you mentioned here, but still no luck.You can refer to the following commit to reproduce the issue https://github.com/DerekQXu/GLSearch/commit/89d2ff9cb74bbcd49f8aac3695d79d565f40025c

And the docker tag,
```
$ docker run buddhiwathsala/glsearch:0.0.2
```
This will output,

```
did not load pdb data
True
True
True
did not load seaborn
Reproduce the issue https://github.com/DerekQXu/GLSearch/issues/2
file_archive('mutag_train_test_mcs_bfs_one_hot_local_degree_profile_None.klepto', {}, cached=True)
```

**Comment by DerekQXu** [comment]
I was able to reproduce the issue again. I solved it by executing the commands directly, rather than through docker.

Does the following work for you? NOTE: please replace `/PATH/TO/GLSEARCH` in the `nvidia-docker run` line.
```
$ git clone https://github.com/BuddhiWathsala/GLSearch.git
$ nvidia-docker build -t tmp_glsearch2 .
Sending build context to Docker daemon  5.314MB
Step 1/7 : FROM nvcr.io/nvidia/pytorch:19.04-py3
 ---> 668e0337f321
Step 2/7 : RUN pip install certifi==2019.3.9 chardet==3.0.4 cycler==0.10.0 decorator==4.4.0 dill==0.2.9 idna==2.8 isodate==0.6.0 kiwisolver==1.0.1 klepto==0.1.6 matplotlib==3.0.3 networkx==2.2 numpy==1.16.2 pandas==0.24.2 Pillow==6.0.0 plyfile==0.7 pox==0.2.5 protobuf==3.7.1 pyparsing==2.3.1 python-dateutil==2.8.0 pytz==2018.9 rdflib==4.2.2 requests==2.21.0 scikit-learn==0.20.3 scipy==1.2.1 six==1.12.0 tensorboardX==1.6 torchvision==0.2.2.post3 torch-cluster==1.2.4 torch-geometric==1.1.2 torch-scatter==1.1.2 torch-sparse==0.2.4 torch-spline-conv==1.0.6 tqdm==4.31.1 urllib3==1.24.1
...
Successfully tagged tmp_glsearch2:latest
$ nvidia-docker run -e "HOSTNAME=$(cat /etc/hostname)" -v /PATH/TO/GLSEARCH:/workspace -it tmp_glsearch2 bash

root@"...":/workspace# cp load/* model/OurMCS/
root@"...":/workspace# cd model/OurMCS/
root@"...":/workspace/model/OurMCS# ls mutag* test.py 
mutag_train_test_mcs_bfs_one_hot_local_degree_profile_None.klepto  test.py
root@"...":/workspace/model/OurMCS# sed -i -e 's/GLSearch//g' test.py
root@"...":/workspace/model/OurMCS# python3 test.py 
did not load pdb data
True
True
True
did not load seaborn
Reproduce the issue https://github.com/DerekQXu//issues/2
file_archive('mutag_train_test_mcs_bfs_one_hot_local_degree_profile_None.klepto', {'train_data': <data_model.OurModelData object at 0x7f556fb52278>, 'test_data': <data_model.OurModelData object at 0x7f549d8ae438>}, cached=True)
```

Thanks!

**Comment by BuddhiWathsala** [comment]
I still couldn't load the data. Could you please share the docker image for that?

**Comment by DerekQXu** [comment]
Uploaded the docker image here: https://hub.docker.com/repository/docker/derekqxu/glsearch_tmp/general

(Note this is the docker file used here, https://github.com/DerekQXu/GLSearch/issues/2#issuecomment-1471014194, not the main repo)

**Comment by BuddhiWathsala** [comment]
I resolved this issue by using `nvidia-docker` instead of the normal `docker`. Thanks, @DerekQXu for your help.
